export const mockAttendanceData = [
  { studentId: "24gcebec219", name: "Alice Johnson", checkInTime: "09:15 AM", status: "Checked In" },
  { studentId: "23gceit229", name: "Bob Smith", checkInTime: "09:32 AM", status: "Checked In" },
  { studentId: "24gcebec220", name: "Carol Davis", checkInTime: "09:45 AM", status: "Checked In" },
  { studentId: "23gceit230", name: "David Wilson", checkInTime: "10:02 AM", status: "Checked In" },
  { studentId: "24gcebec221", name: "Emma Brown", checkInTime: "10:18 AM", status: "Checked In" },
  { studentId: "23gceit231", name: "Frank Miller", checkInTime: "10:35 AM", status: "Checked In" },
  { studentId: "24gcebec222", name: "Grace Lee", checkInTime: "10:52 AM", status: "Checked In" },
  { studentId: "23gceit232", name: "Henry Taylor", checkInTime: "11:10 AM", status: "Checked In" },
  { studentId: "24gcebec223", name: "Iris Anderson", checkInTime: "11:28 AM", status: "Checked In" },
  { studentId: "23gceit233", name: "Jack Martinez", checkInTime: "11:45 AM", status: "Checked In" },
  { studentId: "24gcebec224", name: "Karen White", checkInTime: "12:05 PM", status: "Checked In" },
  { studentId: "23gceit234", name: "Leo Garcia", checkInTime: "12:22 PM", status: "Checked In" },
  { studentId: "24gcebec225", name: "Mia Rodriguez", checkInTime: "01:15 PM", status: "Checked In" },
  { studentId: "23gceit235", name: "Noah Thompson", checkInTime: "01:45 PM", status: "Checked In" },
  { studentId: "24gcebec226", name: "Olivia Harris", checkInTime: "02:10 PM", status: "Checked In" },
]

export const mockStudents = [
  {
    studentId: "24gcebec219",
    name: "Alice Johnson",
    email: "alice@university.edu",
    department: "Computer Science",
    status: "active",
    booksBorrowed: 3,
  },
  {
    studentId: "23gceit229",
    name: "Bob Smith",
    email: "bob@university.edu",
    department: "Engineering",
    status: "active",
    booksBorrowed: 2,
  },
  {
    studentId: "24gcebec220",
    name: "Carol Davis",
    email: "carol@university.edu",
    department: "Business",
    status: "active",
    booksBorrowed: 1,
  },
  {
    studentId: "23gceit230",
    name: "David Wilson",
    email: "david@university.edu",
    department: "Computer Science",
    status: "active",
    booksBorrowed: 4,
  },
  {
    studentId: "24gcebec221",
    name: "Emma Brown",
    email: "emma@university.edu",
    department: "Medicine",
    status: "inactive",
    booksBorrowed: 0,
  },
  {
    studentId: "23gceit231",
    name: "Frank Miller",
    email: "frank@university.edu",
    department: "Law",
    status: "active",
    booksBorrowed: 2,
  },
  {
    studentId: "24gcebec222",
    name: "Grace Lee",
    email: "grace@university.edu",
    department: "Engineering",
    status: "active",
    booksBorrowed: 3,
  },
  {
    studentId: "23gceit232",
    name: "Henry Taylor",
    email: "henry@university.edu",
    department: "Arts",
    status: "active",
    booksBorrowed: 5,
  },
  {
    studentId: "24gcebec223",
    name: "Iris Anderson",
    email: "iris@university.edu",
    department: "Computer Science",
    status: "active",
    booksBorrowed: 2,
  },
  {
    studentId: "23gceit233",
    name: "Jack Martinez",
    email: "jack@university.edu",
    department: "Business",
    status: "inactive",
    booksBorrowed: 0,
  },
  {
    studentId: "24gcebec224",
    name: "Karen White",
    email: "karen@university.edu",
    department: "Medicine",
    status: "active",
    booksBorrowed: 1,
  },
  {
    studentId: "23gceit234",
    name: "Leo Garcia",
    email: "leo@university.edu",
    department: "Engineering",
    status: "active",
    booksBorrowed: 3,
  },
  {
    studentId: "24gcebec225",
    name: "Mia Rodriguez",
    email: "mia@university.edu",
    department: "Computer Science",
    status: "active",
    booksBorrowed: 2,
  },
  {
    studentId: "23gceit235",
    name: "Noah Thompson",
    email: "noah@university.edu",
    department: "Business",
    status: "active",
    booksBorrowed: 1,
  },
  {
    studentId: "24gcebec226",
    name: "Olivia Harris",
    email: "olivia@university.edu",
    department: "Arts",
    status: "active",
    booksBorrowed: 4,
  },
]

export const mockBooks = [
  {
    isbn: "978-0-13-110362-7",
    title: "The C Programming Language",
    author: "Brian W. Kernighan",
    category: "Programming",
    status: "borrowed",
    borrowedBy: "Alice Johnson",
    dueDate: "2025-11-15",
  },
  {
    isbn: "978-0-201-63361-0",
    title: "Design Patterns",
    author: "Gang of Four",
    category: "Software Design",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
  {
    isbn: "978-0-596-00712-6",
    title: "Learning Python",
    author: "Mark Lutz",
    category: "Programming",
    status: "borrowed",
    borrowedBy: "David Wilson",
    dueDate: "2025-11-20",
  },
  {
    isbn: "978-1-491-95023-9",
    title: "Eloquent JavaScript",
    author: "Marijn Haverbeke",
    category: "Programming",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
  {
    isbn: "978-0-13-235088-4",
    title: "Clean Code",
    author: "Robert C. Martin",
    category: "Software Development",
    status: "borrowed",
    borrowedBy: "Henry Taylor",
    dueDate: "2025-11-10",
  },
  {
    isbn: "978-0-262-03384-8",
    title: "Introduction to Algorithms",
    author: "Cormen, Leiserson, Rivest, Stein",
    category: "Algorithms",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
  {
    isbn: "978-0-596-52068-7",
    title: "RESTful Web Services",
    author: "Leonard Richardson",
    category: "Web Development",
    status: "borrowed",
    borrowedBy: "Grace Lee",
    dueDate: "2025-11-18",
  },
  {
    isbn: "978-1-449-35818-8",
    title: "You Don't Know JS",
    author: "Kyle Simpson",
    category: "JavaScript",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
  {
    isbn: "978-0-13-468599-1",
    title: "Refactoring",
    author: "Martin Fowler",
    category: "Software Development",
    status: "borrowed",
    borrowedBy: "Alice Johnson",
    dueDate: "2025-11-22",
  },
  {
    isbn: "978-1-491-95019-2",
    title: "Practical Machine Learning",
    author: "Aurélien Géron",
    category: "Machine Learning",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
  {
    isbn: "978-0-13-595705-9",
    title: "The Pragmatic Programmer",
    author: "David Thomas, Andrew Hunt",
    category: "Software Development",
    status: "borrowed",
    borrowedBy: "Leo Garcia",
    dueDate: "2025-11-12",
  },
  {
    isbn: "978-1-491-95017-8",
    title: "Deep Learning",
    author: "Ian Goodfellow",
    category: "Machine Learning",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
  {
    isbn: "978-0-596-00712-7",
    title: "Web Development with Node.js",
    author: "Ethan Brown",
    category: "Web Development",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
  {
    isbn: "978-1-491-95020-8",
    title: "Data Science Handbook",
    author: "Jake VanderPlas",
    category: "Data Science",
    status: "borrowed",
    borrowedBy: "Mia Rodriguez",
    dueDate: "2025-11-25",
  },
  {
    isbn: "978-0-13-110363-4",
    title: "Advanced C Programming",
    author: "Richard Reese",
    category: "Programming",
    status: "available",
    borrowedBy: null,
    dueDate: null,
  },
]
